Freeze how many messages allowed in uncleaned packages
Signed-off-by: Waldz <valdas@mysterium.network>

diff --git a/bin/check_lint b/bin/check_lint
--- a/bin/check_lint
+++ b/bin/check_lint
@@ -14,37 +14,52 @@
 
 source bin/helpers/output.sh
 
+check_uncleaned_package () {
+    PACKAGE=$1
+    PACKAGE_MESSAGES_MAX=$2
+
+    PACKAGE_MESSAGES=`echo "${MESSAGES_ERROR}" | grep "${PACKAGE}"`
+    PACKAGE_MESSAGES_COUNT=`echo -n "${PACKAGE_MESSAGES}" | grep -c '^'`
+    print_warning "[warning] ${PACKAGE_MESSAGES_COUNT} messages in '${PACKAGE}': \n${PACKAGE_MESSAGES}\n"
+
+    MESSAGES_ERROR=`echo -n "${MESSAGES_ERROR}" | grep -v "${PACKAGE}"`
+    if [ ${PACKAGE_MESSAGES_COUNT} -eq 0 ]; then
+        MESSAGES_RECONFIGURE+=("Congratulations! Cleaned all errors in package '${PACKAGE}'")
+    elif [ ${PACKAGE_MESSAGES_COUNT} -lt ${PACKAGE_MESSAGES_MAX} ]; then
+        MESSAGES_RECONFIGURE+=("Congratulations! Decreased ${PACKAGE_MESSAGES_MAX}->${PACKAGE_MESSAGES_COUNT} errors in package '${PACKAGE}'")
+    elif [ ${PACKAGE_MESSAGES_COUNT} -gt ${PACKAGE_MESSAGES_MAX} ]; then
+        MESSAGES_RECONFIGURE+=("Sad :(. Increased ${PACKAGE_MESSAGES_MAX}->${PACKAGE_MESSAGES_COUNT} errors in package '${PACKAGE}'")
+    fi
+}
+
 ARGUMENTS=$@
 if [ -z "$ARGUMENTS" ]; then
     ARGUMENTS=`go list ./...`
 fi
 
-MESSAGES=`golint --set_exit_status --min_confidence=1 ${ARGUMENTS} 2>/dev/null`
+MESSAGES_ERROR=`golint --set_exit_status --min_confidence=1 ${ARGUMENTS} 2>/dev/null`
+MESSAGES_RECONFIGURE=()
 
-PACKAGES_IN_CLEANING_MODE=(
-    "github.com/mysterium/node/cmd"
-    "github.com/mysterium/node/identity"
-    "github.com/mysterium/node/tequilapi"
-    "github.com/mysterium/node/session"
-    "github.com/mysterium/node/service_discovery/dto"
-    "github.com/mysterium/node/server/dto"
-    "github.com/mysterium/node/openvpn"
-    "github.com/mysterium/node/nat"
-    "github.com/mysterium/node/money"
-    "github.com/mysterium/node/ip"
-    "github.com/mysterium/node/location"
-)
-for PACKAGE in ${PACKAGES_IN_CLEANING_MODE[*]}; do
-    PACKAGE_MESSAGES=`echo -n "${MESSAGES}" | grep "${PACKAGE}"`
-    PACKAGE_MESSAGES_COUNT=`echo "${PACKAGE_MESSAGES}" | wc -l | awk '{ print $1 }'`
-    print_warning "[warning] ${PACKAGE_MESSAGES_COUNT} messages in '${PACKAGE}': \n${PACKAGE_MESSAGES}\n"
+check_uncleaned_package "github.com/mysterium/node/cmd" 3
+check_uncleaned_package "github.com/mysterium/node/identity" 9
+check_uncleaned_package "github.com/mysterium/node/tequilapi" 10
+check_uncleaned_package "github.com/mysterium/node/session" 6
+check_uncleaned_package "github.com/mysterium/node/service_discovery/dto" 13
+check_uncleaned_package "github.com/mysterium/node/server/dto" 6
+check_uncleaned_package "github.com/mysterium/node/openvpn" 49
+check_uncleaned_package "github.com/mysterium/node/nat" 5
+check_uncleaned_package "github.com/mysterium/node/money" 4
+check_uncleaned_package "github.com/mysterium/node/ip" 4
+check_uncleaned_package "github.com/mysterium/node/location" 1
 
-    MESSAGES=`echo -n "${MESSAGES}" | grep -v "${PACKAGE}"`
-done
+MESSAGES_ERROR_COUNT=`echo -n "${MESSAGES_ERROR}" | grep -c '^'`
+if [ ${MESSAGES_ERROR_COUNT} -gt 0 ]; then
+    print_error "[error] ${MESSAGES_COUNT} messages: ${MESSAGES_ERROR}"
+    exit 1
+fi
 
-MESSAGES_COUNT=`echo -n "${MESSAGES}" | wc -l | awk '{ print $1 }'`
-if [ ${MESSAGES_COUNT} -gt 0 ]; then
-    print_error "[error] ${MESSAGES_COUNT} messages: ${MESSAGES}"
+if [ ${#MESSAGES_RECONFIGURE[@]} -gt 0 ]; then
+    IFS=$'\n'; print_error "[error] Should reconfigure uncleaned packages: \n${MESSAGES_RECONFIGURE[*]}\n"
     exit 1
 fi
 
